[package]
name = "buckle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "buckle"

[dependencies]
clap = "3.0.0-beta.4"
directories-next = "2.0"
futures = "0.3"
gtmpl = "0.7"
human-errors = "0.1.1"
http = "0.2"
itertools = "0.10"
lazy_static = "1.4"
libhoney-rust = "0.1"
nix = "0.22.1"
once_cell = "1.8"
opentelemetry = { version = "0.16", features = ["rt-tokio"] }
opentelemetry-application-insights = { version = "0.17", features = ["reqwest-client"] }
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls", "json", "blocking"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.8"
solvent = "0.8"
shell-words = "1.0"
tracing = "0.1"
walkdir = "2.3"
tracing-honeycomb = { git = "https://github.com/notheotherben/tracing-honeycomb" }
tracing-opentelemetry = "0.15"
tracing-subscriber = "0.2"

[dev-dependencies]
mocktopus = "0.7.11"
tempfile = "3.2"

[profile.release]
debug = true