[package]
name = "buckle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "buckle"

[dependencies]
clap = { version = "3.2.8", features = ["cargo", "env"] }
directories-next = "2.0"
dunce = "1.0"
futures = "0.3"
gethostname = "0.2"
gtmpl = "0.7"
human-errors = "0.1.3"
http = "0.2"
itertools = "0.10"
lazy_static = "1.4"
nix = "0.24.2"
once_cell = "1.13"
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.10", features = ["tonic", "tls"] }
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "json", "blocking"] }
rustls = "0.20"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.8"
solvent = "0.8"
shell-words = "1.1"
tokio = "1"
tonic = { version = "0.7.2", features = ["transport", "tls"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = "0.3"
walkdir = "2.3"
webpki-roots = "0.22"

[dev-dependencies]
mocktopus = { git = "https://github.com/notheotherben/mocktopus.git" }
tempfile = "3.3"

[profile.release]
debug = true