[package]
name = "buckle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "buckle"

[dependencies]
clap = "3.0.0-beta.4"
directories-next = "2.0"
dunce = "1.0"
futures = "0.3"
gethostname = "0.2"
gtmpl = "0.7"
human-errors = "0.1.1"
http = "0.2"
itertools = "0.10"
lazy_static = "1.4"
nix = "0.23.0"
once_cell = "1.8"
opentelemetry = { version = "0.16", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.9", features = ["tonic", "tls"] }
opentelemetry-application-insights = { version = "0.18", features = ["reqwest-client"] }
reqwest = { version = "0.11.5", default-features = false, features = ["rustls-tls", "json", "blocking"] }
rustls = "0.19"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.8"
solvent = "0.8"
shell-words = "1.0"
tokio = "1"
tonic = { version = "0.5", features = ["transport", "tls"] }
tracing = "0.1"
tracing-opentelemetry = "0.15"
tracing-subscriber = "0.2"
walkdir = "2.3"
webpki-roots = "0.21"

[dev-dependencies]
mocktopus = "0.7.11"
tempfile = "3.2"

[profile.release]
debug = true