name: Release
on:
  release:
    types: [published]
jobs:
  version:
    name: Start Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v7.0.0

      - name: Generate Package Version
        shell: pwsh
        run: Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$('${{ github.event.release.tag_name }}'.substring(1))"

      - name: Set Package Version
        run: sed -i "s/^version\s*=\s*\".*\"/version = \"$VERSION\"/g" Cargo.toml

      - name: Stash Versioned Cargo.toml
        uses: actions/upload-artifact@v7
        with:
          name: cargofile
          path: Cargo.toml

  build:
    name: ${{ matrix.os }}-${{ matrix.arch }}-release
    runs-on: ${{ matrix.run_on }}
    continue-on-error: true
    needs:
      - version
    strategy:
      matrix:
        include:
          # Windows builds
          - arch: amd64
            os: windows
            run_on: windows-latest
            target: x86_64-pc-windows-msvc
            extension: .exe

          # Linux builds
          - arch: amd64
            run_on: ubuntu-latest
            os: linux
            dockerfile: build/Dockerfile.linux-x86_64
          - arch: arm64
            run_on: ubuntu-latest
            os: linux
            target: aarch64-unknown-linux-gnu
            cross: true

          # Apple MacOS builds
          - arch: amd64
            run_on: macos-latest
            os: darwin
            target: x86_64-apple-darwin
          - arch: arm64
            run_on: macos-latest
            os: darwin
            target: aarch64-apple-darwin
    steps:
      - name: setup dependencies
        run: ${{ matrix.setup }}
        if: matrix.setup

      - name: Get Rust Stable
        uses: dtolnay/rust-toolchain@stable
        if: matrix.target
        with:
          targets: ${{ matrix.target }}

      - name: Check out code
        uses: actions/checkout@v7.0.0

      - name: Fetch Versioned Cargo.toml
        uses: actions/download-artifact@v8
        with:
          name: cargofile

      - name: install protoc
        if: ${{ matrix.target && !matrix.cross }}
        uses: SierraSoftworks/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install cargo-binstall
        if: matrix.cross
        uses: cargo-bins/cargo-binstall@main

      - name: install cross
        if: matrix.cross
        run: cargo binstall --no-confirm cross
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cache ~/.cargo
        if: matrix.target
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: cargo build
        if: matrix.target
        run: ${{ matrix.cross && 'cross' || 'cargo' }} build --release --target ${{ matrix.target }} ${{ matrix.flags }}
          
      - name: Reclaim cache ownership from cross
        if: matrix.cross
        run: sudo chown -R "$(id -u):$(id -g)" "$HOME/.cargo" target

      - name: Strip Debug Symbols
        run: |
          ${{ matrix.strip }} target/${{ matrix.target }}/release/buckle${{ matrix.extension }}
        if: matrix.strip

      - name: Build Docker image
        run: |
          docker build -t buckle:dev -f ${{ matrix.dockerfile }} .
          mkdir -p out
          docker run --rm -v $(pwd):/buckle buckle:dev cp /app/buckle /buckle/out/buckle${{ matrix.extension }}
        if: matrix.dockerfile

      - name: Prepare release artifacts
        run: |
          mkdir -p out
          cp target/${{ matrix.target }}/release/buckle${{ matrix.extension }} out/buckle${{ matrix.extension }}
        if: matrix.target

      - name: Upload GitHub Release Artifacts
        uses: SierraSoftworks/gh-releases@v1.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: "true"
          files: |
            out/buckle${{ matrix.extension }} | buckle-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}

  tap:
    name: Update Homebrew Tap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Update Homebrew Tap
        uses: SierraSoftworks/actions-tap@v1
        with:
          app-id: ${{ secrets.TAP_APP_ID }}
          private-key: ${{ secrets.TAP_APP_PRIVATE_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          aliases: major minor
